### PR TITLE
Added TimeTotal (ms) to result.

### PR DESCRIPTION
**Pull request by rajder**
Hello, this is a pull request originating from: https://github.com/bosun-monitor/bosun/pull/1263

### CODE REVIEW

**Comment by dimamedvedev** [comment]
What's needed for this merge? Maybe also add response size field?

**Comment by tlimoncelli** [comment]
Is something missing from the PR?  I see the TimeTotal being collected but it is never output anywhere.  Could you add something to cmd/httpunit/main.go that outputs it?

Thanks!

**Comment by rajder** [comment]
Hi, sorry for the delay I had other projects keeping me busy for a while.

@tlimoncelli I completely missed the command line utility part of this repository, I thought it was a library and nothing more. I'm using this code as part of the bosun code base where I added the new metric but was asked to make the change to this repos instead. BR /AR

**Comment by tlimoncelli** [comment]
No worries.  The command line utility can be used to just verify the library works.  Though, I use it as a debugging tool :-)

**Pull request merged**
